
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Akirs.client.DL
{

using System;
    using System.Collections.Generic;
    
public partial class ActivityLog
{

    public long Itbid { get; set; }

    public Nullable<int> BankId { get; set; }

    public string Acct_no { get; set; }

    public string Trans_Ref_no { get; set; }

    public Nullable<System.DateTime> RequestTime { get; set; }

    public Nullable<System.DateTime> ResponseTime { get; set; }

    public string PAN { get; set; }

    public Nullable<int> ISOType { get; set; }

    public string IPAddress { get; set; }

    public Nullable<int> PortNo { get; set; }

    public Nullable<int> ResponseCode { get; set; }

    public string AvailableBal { get; set; }

}

}
