

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Akirs.client.DL
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class AKIRSTAXEntities : DbContext
{
    public AKIRSTAXEntities()
        : base("name=AKIRSTAXEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }

    public virtual DbSet<AccountType> AccountTypes { get; set; }

    public virtual DbSet<Application> Applications { get; set; }

    public virtual DbSet<AspNetRole> AspNetRoles { get; set; }

    public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }

    public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }

    public virtual DbSet<AssessmentComp> AssessmentComps { get; set; }

    public virtual DbSet<BankBranch> BankBranches { get; set; }

    public virtual DbSet<BankCharge> BankCharges { get; set; }

    public virtual DbSet<BankRole> BankRoles { get; set; }

    public virtual DbSet<Bank> Banks { get; set; }

    public virtual DbSet<BankTransactionType> BankTransactionTypes { get; set; }

    public virtual DbSet<BankType> BankTypes { get; set; }

    public virtual DbSet<BankUserprofile> BankUserprofiles { get; set; }

    public virtual DbSet<Charge> Charges { get; set; }

    public virtual DbSet<City> Cities { get; set; }

    public virtual DbSet<CompanyData> CompanyDatas { get; set; }

    public virtual DbSet<Currency> Currencies { get; set; }

    public virtual DbSet<DBAudit> DBAudits { get; set; }

    public virtual DbSet<EmailMessage> EmailMessages { get; set; }

    public virtual DbSet<ExceptionLog> ExceptionLogs { get; set; }

    public virtual DbSet<FamilyDetail> FamilyDetails { get; set; }

    public virtual DbSet<Membership> Memberships { get; set; }

    public virtual DbSet<menucontrol> menucontrols { get; set; }

    public virtual DbSet<Profile> Profiles { get; set; }

    public virtual DbSet<RemoteBank> RemoteBanks { get; set; }

    public virtual DbSet<roleAssignment> roleAssignments { get; set; }

    public virtual DbSet<RoleLimit> RoleLimits { get; set; }

    public virtual DbSet<RoleReportToLog> RoleReportToLogs { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Salaryupload_temp> Salaryupload_temp { get; set; }

    public virtual DbSet<SALARYUPLOADHISTORY> SALARYUPLOADHISTORies { get; set; }

    public virtual DbSet<SMSMessage> SMSMessages { get; set; }

    public virtual DbSet<State> States { get; set; }

    public virtual DbSet<tbl_BankCharges> tbl_BankCharges { get; set; }

    public virtual DbSet<tbl_Roles> tbl_Roles { get; set; }

    public virtual DbSet<tbl_userLogin> tbl_userLogin { get; set; }

    public virtual DbSet<TestImage> TestImages { get; set; }

    public virtual DbSet<TransactionType> TransactionTypes { get; set; }

    public virtual DbSet<UserRole> UserRoles { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UsersInRole> UsersInRoles { get; set; }

    public virtual DbSet<WHTUPLOAD> WHTUPLOADs { get; set; }

    public virtual DbSet<ActivityLog> ActivityLogs { get; set; }

    public virtual DbSet<Country> Countries { get; set; }

    public virtual DbSet<gb> gbs { get; set; }

    public virtual DbSet<MaritalStatu> MaritalStatus { get; set; }

    public virtual DbSet<MFBPANMAPPING> MFBPANMAPPINGs { get; set; }

    public virtual DbSet<Ministry> Ministries { get; set; }

    public virtual DbSet<Profession> Professions { get; set; }

    public virtual DbSet<RelationShip> RelationShips { get; set; }

    public virtual DbSet<RevenueHead> RevenueHeads { get; set; }

    public virtual DbSet<TaxType> TaxTypes { get; set; }

    public virtual DbSet<AspNetUser> AspNetUsers { get; set; }

    public virtual DbSet<Notification> Notifications { get; set; }

    public virtual DbSet<NotificationLog> NotificationLogs { get; set; }

    public virtual DbSet<RentPrice> RentPrices { get; set; }

    public virtual DbSet<EnrollmentLog> EnrollmentLogs { get; set; }

    public virtual DbSet<WHTUPLOAD_temp> WHTUPLOAD_temp { get; set; }

    public virtual DbSet<WHTUPLOADHISTORY> WHTUPLOADHISTORies { get; set; }

    public virtual DbSet<NotificationProvider> NotificationProviders { get; set; }

    public virtual DbSet<AssessmentRecord> AssessmentRecords { get; set; }

    public virtual DbSet<TransactionLog> TransactionLogs { get; set; }

    public virtual DbSet<IncomeSourceType> IncomeSourceTypes { get; set; }

    public virtual DbSet<IncomeSource> IncomeSources { get; set; }

    public virtual DbSet<IncomePayment> IncomePayments { get; set; }

    public virtual DbSet<SALARYUPLOAD> SALARYUPLOADs { get; set; }

    public virtual DbSet<SALARYUPLOAD_HISTORY> SALARYUPLOAD_HISTORY { get; set; }


    public virtual ObjectResult<proc_BankTransactionType_Result> proc_BankTransactionType(Nullable<int> bankid)
    {

        var bankidParameter = bankid.HasValue ?
            new ObjectParameter("bankid", bankid) :
            new ObjectParameter("bankid", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_BankTransactionType_Result>("proc_BankTransactionType", bankidParameter);
    }


    public virtual int proc_CustomerInfoByAccountNo2(string accountnumber, Nullable<int> bankfiid)
    {

        var accountnumberParameter = accountnumber != null ?
            new ObjectParameter("accountnumber", accountnumber) :
            new ObjectParameter("accountnumber", typeof(string));


        var bankfiidParameter = bankfiid.HasValue ?
            new ObjectParameter("bankfiid", bankfiid) :
            new ObjectParameter("bankfiid", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_CustomerInfoByAccountNo2", accountnumberParameter, bankfiidParameter);
    }


    public virtual ObjectResult<proc_EnrollmentList_Result> proc_EnrollmentList()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_EnrollmentList_Result>("proc_EnrollmentList");
    }


    public virtual ObjectResult<PROC_EnrollmentListByID_Result> PROC_EnrollmentListByID(string enrollmentID)
    {

        var enrollmentIDParameter = enrollmentID != null ?
            new ObjectParameter("EnrollmentID", enrollmentID) :
            new ObjectParameter("EnrollmentID", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PROC_EnrollmentListByID_Result>("PROC_EnrollmentListByID", enrollmentIDParameter);
    }


    public virtual ObjectResult<proc_MfbBankCharges_Result> proc_MfbBankCharges(Nullable<long> bankID)
    {

        var bankIDParameter = bankID.HasValue ?
            new ObjectParameter("BankID", bankID) :
            new ObjectParameter("BankID", typeof(long));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_MfbBankCharges_Result>("proc_MfbBankCharges", bankIDParameter);
    }


    public virtual ObjectResult<rolemenu_Result> rolemenu(Nullable<int> roleid, Nullable<int> coyid)
    {

        var roleidParameter = roleid.HasValue ?
            new ObjectParameter("roleid", roleid) :
            new ObjectParameter("roleid", typeof(int));


        var coyidParameter = coyid.HasValue ?
            new ObjectParameter("coyid", coyid) :
            new ObjectParameter("coyid", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rolemenu_Result>("rolemenu", roleidParameter, coyidParameter);
    }


    public virtual ObjectResult<rolemenu2_Result> rolemenu2(Nullable<int> roleid, Nullable<int> coyid)
    {

        var roleidParameter = roleid.HasValue ?
            new ObjectParameter("roleid", roleid) :
            new ObjectParameter("roleid", typeof(int));


        var coyidParameter = coyid.HasValue ?
            new ObjectParameter("coyid", coyid) :
            new ObjectParameter("coyid", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<rolemenu2_Result>("rolemenu2", roleidParameter, coyidParameter);
    }


    public virtual ObjectResult<proc_GetCompanyName_Result> proc_GetCompanyName(string companyname)
    {

        var companynameParameter = companyname != null ?
            new ObjectParameter("companyname", companyname) :
            new ObjectParameter("companyname", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_GetCompanyName_Result>("proc_GetCompanyName", companynameParameter);
    }


    public virtual ObjectResult<proc_GetNextEnRoll_Result> proc_GetNextEnRoll()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_GetNextEnRoll_Result>("proc_GetNextEnRoll");
    }


    public virtual ObjectResult<NotificationAlert_Result> NotificationAlert()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NotificationAlert_Result>("NotificationAlert");
    }


    public virtual ObjectResult<proc_Notification_Result> proc_Notification(string notificationType, string email, string phoneno, string notificationmsg, string userid)
    {

        var notificationTypeParameter = notificationType != null ?
            new ObjectParameter("NotificationType", notificationType) :
            new ObjectParameter("NotificationType", typeof(string));


        var emailParameter = email != null ?
            new ObjectParameter("Email", email) :
            new ObjectParameter("Email", typeof(string));


        var phonenoParameter = phoneno != null ?
            new ObjectParameter("phoneno", phoneno) :
            new ObjectParameter("phoneno", typeof(string));


        var notificationmsgParameter = notificationmsg != null ?
            new ObjectParameter("notificationmsg", notificationmsg) :
            new ObjectParameter("notificationmsg", typeof(string));


        var useridParameter = userid != null ?
            new ObjectParameter("userid", userid) :
            new ObjectParameter("userid", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_Notification_Result>("proc_Notification", notificationTypeParameter, emailParameter, phonenoParameter, notificationmsgParameter, useridParameter);
    }


    public virtual ObjectResult<Proc_UpdateNotification_Result> Proc_UpdateNotification(Nullable<int> itbid)
    {

        var itbidParameter = itbid.HasValue ?
            new ObjectParameter("Itbid", itbid) :
            new ObjectParameter("Itbid", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_UpdateNotification_Result>("Proc_UpdateNotification", itbidParameter);
    }


    public virtual ObjectResult<string> proc_getPayYear(string enrollmentID)
    {

        var enrollmentIDParameter = enrollmentID != null ?
            new ObjectParameter("enrollmentID", enrollmentID) :
            new ObjectParameter("enrollmentID", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("proc_getPayYear", enrollmentIDParameter);
    }


    public virtual ObjectResult<proc_computeAssessment_Result> proc_computeAssessment(string enrollmentID, string yearValue)
    {

        var enrollmentIDParameter = enrollmentID != null ?
            new ObjectParameter("enrollmentID", enrollmentID) :
            new ObjectParameter("enrollmentID", typeof(string));


        var yearValueParameter = yearValue != null ?
            new ObjectParameter("yearValue", yearValue) :
            new ObjectParameter("yearValue", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_computeAssessment_Result>("proc_computeAssessment", enrollmentIDParameter, yearValueParameter);
    }


    public virtual ObjectResult<proc_computeAssessment_modification_Result> proc_computeAssessment_modification(string enrollmentID, string yearValue)
    {

        var enrollmentIDParameter = enrollmentID != null ?
            new ObjectParameter("enrollmentID", enrollmentID) :
            new ObjectParameter("enrollmentID", typeof(string));


        var yearValueParameter = yearValue != null ?
            new ObjectParameter("yearValue", yearValue) :
            new ObjectParameter("yearValue", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_computeAssessment_modification_Result>("proc_computeAssessment_modification", enrollmentIDParameter, yearValueParameter);
    }

}

}

