//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akirs.client.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertLog
    {
        public long itbid { get; set; }
        public string MessageType { get; set; }
        public string MessageSubject { get; set; }
        public string MessageDesc { get; set; }
        public string RequireTemplate { get; set; }
        public string MessageTemplate { get; set; }
        public string SenderEmail { get; set; }
        public string ReceiverEmail { get; set; }
        public string SenderPhone { get; set; }
        public string ReceiverPhone { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreatedBy { get; set; }
        public string Status { get; set; }
    }
}
