
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Akirs.client.DL
{

using System;
    using System.Collections.Generic;
    
public partial class AssessmentRecord
{

    public string enrollmentID { get; set; }

    public decimal Income { get; set; }

    public decimal GrossIncome { get; set; }

    public decimal ConsolidateAllowance { get; set; }

    public decimal TotalFPA { get; set; }

    public decimal TaxableIncome { get; set; }

    public decimal MinimumTax { get; set; }

    public decimal C7PercON { get; set; }

    public decimal C11PercON { get; set; }

    public decimal C15PercON { get; set; }

    public decimal C19PercON { get; set; }

    public decimal C21PercON { get; set; }

    public decimal C24PercON { get; set; }

    public decimal TaxableLiab { get; set; }

    public decimal TaxableLiabMonth { get; set; }

    public decimal LogisticTest1 { get; set; }

    public decimal LogisticTest2 { get; set; }

    public decimal NetTax { get; set; }

    public int Itbid { get; set; }

    public Nullable<int> counter { get; set; }

    public string EmployeeName { get; set; }

    public Nullable<decimal> NontaxableIncome { get; set; }

    public Nullable<decimal> IncomePaid { get; set; }

    public Nullable<decimal> IncomeDifference { get; set; }

}

}
