
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Akirs.client.DL
{

using System;
    using System.Collections.Generic;
    
public partial class AssessmentComp
{

    public int ItbID { get; set; }

    public Nullable<decimal> GrossIncome_rate { get; set; }

    public Nullable<decimal> MinTax_rate { get; set; }

    public Nullable<decimal> FPA_Amount { get; set; }

    public Nullable<decimal> PensionRate { get; set; }

    public Nullable<decimal> Level1Tax_rate { get; set; }

    public Nullable<decimal> Level1Tax_Amount { get; set; }

    public Nullable<decimal> Level2Tax_rate { get; set; }

    public Nullable<decimal> Level2Tax_Amount { get; set; }

    public Nullable<decimal> Level3Tax_rate { get; set; }

    public Nullable<decimal> Level3Tax_Amount { get; set; }

    public Nullable<decimal> Level4Tax_rate { get; set; }

    public Nullable<decimal> Level4Tax_Amount { get; set; }

    public Nullable<decimal> Level5Tax_rate { get; set; }

    public Nullable<decimal> Level5Tax_Amount { get; set; }

    public Nullable<decimal> Level6Tax_rate { get; set; }

    public Nullable<decimal> Level6Tax_Amount { get; set; }

    public Nullable<System.DateTime> Last_Modified_Date { get; set; }

    public string Last_Modified_Authid { get; set; }

    public string Last_Modified_Uid { get; set; }

    public string Status { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

}

}
