
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Akirs.client.DL
{

using System;
    using System.Collections.Generic;
    
public partial class BankCharge
{

    public long itbID { get; set; }

    public long BankID { get; set; }

    public string TransactionCode { get; set; }

    public int ChargeCode { get; set; }

    public int ChargeBasis { get; set; }

    public Nullable<decimal> ChargeToCustomer { get; set; }

    public Nullable<decimal> BankCommission { get; set; }

    public Nullable<decimal> MainBankCommission { get; set; }

    public string Status { get; set; }

    public System.DateTime Createdate { get; set; }

    public string AdminUserID { get; set; }

    public string AuthUserID { get; set; }

}

}
