
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Akirs.client.DL
{

using System;
    using System.Collections.Generic;
    
public partial class BankBranch
{

    public long itbID { get; set; }

    public long BankID { get; set; }

    public string BranchCode { get; set; }

    public string BranchName { get; set; }

    public string Address { get; set; }

    public Nullable<int> StateCode { get; set; }

    public Nullable<int> CityCode { get; set; }

    public string ContactPerson { get; set; }

    public string ContactPhone { get; set; }

    public string ContactEmail { get; set; }

    public Nullable<bool> IsMain { get; set; }

    public string Status { get; set; }

    public System.DateTime Createdate { get; set; }

    public string AdminUserID { get; set; }

    public string AuthUserID { get; set; }

}

}
