
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Akirs.client.DL
{

using System;
    using System.Collections.Generic;
    
public partial class Bank
{

    public long itbID { get; set; }

    public long BankID { get; set; }

    public string ProviderID { get; set; }

    public string BankName { get; set; }

    public string CBNCode { get; set; }

    public string Address { get; set; }

    public Nullable<int> StateCode { get; set; }

    public Nullable<int> CityCode { get; set; }

    public string ContactPerson { get; set; }

    public string ContactPhone { get; set; }

    public string ContactEmail { get; set; }

    public int BankType { get; set; }

    public string Weburl { get; set; }

    public string WebserviceUrl { get; set; }

    public string Status { get; set; }

    public System.DateTime Createdate { get; set; }

    public string AdminUserID { get; set; }

    public string AuthUserID { get; set; }

    public string WebSecurityID { get; set; }

    public string WebSecurityPassword { get; set; }

    public string ZenInterfaceAcct { get; set; }

    public string ZenSettlementAccount { get; set; }

    public string MfbCoreSettlementAcct { get; set; }

    public Nullable<decimal> AccountLimit { get; set; }

    public string ZenSetAcctType { get; set; }

    public string ZenIntAcctType { get; set; }

    public string MfbAcctType { get; set; }

    public Nullable<int> ATM_TYPE { get; set; }

    public Nullable<int> AtmConnectionType { get; set; }

    public string IPAddress { get; set; }

    public string PortNo { get; set; }

    public string PAN { get; set; }

}

}
