
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Akirs.client.DL
{

using System;
    using System.Collections.Generic;
    
public partial class BankTransactionType
{

    public long itbID { get; set; }

    public string TransactionCode { get; set; }

    public long BankID { get; set; }

    public string DafaultNarration { get; set; }

    public string ZenSettlementAcct { get; set; }

    public string MfbSettlementAcct { get; set; }

    public string ZenAcctType { get; set; }

    public string MfbAcctType { get; set; }

    public Nullable<decimal> DailyTranxLimit { get; set; }

    public Nullable<decimal> CumDailyTranxLimit { get; set; }

    public string Status { get; set; }

    public System.DateTime Createdate { get; set; }

    public string AdminUserID { get; set; }

    public string AuthUserID { get; set; }

    public Nullable<bool> SelectedFlag { get; set; }

}

}
