
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Akirs.client.DL
{

using System;
    using System.Collections.Generic;
    
public partial class CompanyData
{

    public int ItbID { get; set; }

    public string TIN_NO { get; set; }

    public string CompanyName { get; set; }

    public string TINVerificationstatus { get; set; }

    public int TaxtypeID { get; set; }

    public string CompanyAddress { get; set; }

    public string CompanyPhonenumber { get; set; }

    public string CompanyAltNumber { get; set; }

    public string CompanyEmail { get; set; }

    public string CompanyAltEmail { get; set; }

    public string CompanyRegNo { get; set; }

    public Nullable<System.DateTime> CompanyStartDate { get; set; }

    public Nullable<System.DateTime> Last_Modified_Date { get; set; }

    public string Last_Modified_Authid { get; set; }

    public string Last_Modified_Uid { get; set; }

    public string Status { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public string AuthUserID { get; set; }

}

}
