
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Akirs.client.DL
{

using System;
    using System.Collections.Generic;
    
public partial class Currency
{

    public long itbID { get; set; }

    public string CurrencyCode { get; set; }

    public string CurrencyName { get; set; }

    public string CurrencySymbol { get; set; }

    public string Status { get; set; }

    public System.DateTime Createdate { get; set; }

    public string AdminUserID { get; set; }

    public string AuthUserID { get; set; }

}

}
