
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Akirs.client.DL
{

using System;
    using System.Collections.Generic;
    
public partial class EmailMessage
{

    public long itbid { get; set; }

    public string EmailContent { get; set; }

    public string EmailAddress { get; set; }

    public string emailPlatform { get; set; }

    public string EmailStatus { get; set; }

    public Nullable<System.DateTime> EntryDate { get; set; }

    public Nullable<bool> HasAttachment { get; set; }

    public byte[] Attachment { get; set; }

    public string FromAddress { get; set; }

    public string emailSubject { get; set; }

    public string bankfiid { get; set; }

    public Nullable<int> nostrial { get; set; }

}

}
