
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Akirs.client.DL
{

using System;
    using System.Collections.Generic;
    
public partial class EnrollmentLog
{

    public int ItbID { get; set; }

    public string EnrollmentID { get; set; }

    public int TaxtypeID { get; set; }

    public string Firstname { get; set; }

    public string Middlename { get; set; }

    public string Lastname { get; set; }

    public string Address { get; set; }

    public string Phonenumber { get; set; }

    public string Email { get; set; }

    public string CountryID { get; set; }

    public Nullable<System.DateTime> DateOfBirth { get; set; }

    public Nullable<int> ProfessionID { get; set; }

    public Nullable<int> CompanyID { get; set; }

    public string Companyname { get; set; }

    public string MaritalStatus { get; set; }

    public string Gender { get; set; }

    public string Position { get; set; }

    public Nullable<int> Numberofchildren { get; set; }

    public Nullable<System.DateTime> Last_Modified_Date { get; set; }

    public string Last_Modified_Authid { get; set; }

    public string Last_Modified_Uid { get; set; }

    public string Status { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public string AuthUserID { get; set; }

    public Nullable<decimal> AMOUNTDUE { get; set; }

    public Nullable<decimal> LASTPAYAMOUNT { get; set; }

    public Nullable<System.DateTime> LASTPAYDATE { get; set; }

    public Nullable<decimal> NETTAX { get; set; }

    public string StateCode { get; set; }

    public string CityCode { get; set; }

    public Nullable<int> AddressType { get; set; }

    public string LGACode { get; set; }

    public Nullable<int> RentRangeId { get; set; }

}

}
