
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Akirs.client.DL
{

using System;
    using System.Collections.Generic;
    
public partial class ExceptionLog
{

    public long ExceptionId { get; set; }

    public string PageName { get; set; }

    public string ExceptionMessage { get; set; }

    public Nullable<System.DateTime> ExceptionDate { get; set; }

    public string UserId { get; set; }

}

}
