
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Akirs.client.DL
{

using System;
    using System.Collections.Generic;
    
public partial class FamilyDetail
{

    public int ItbID { get; set; }

    public string EnrollmentID { get; set; }

    public string FullName { get; set; }

    public Nullable<int> Age { get; set; }

    public int RelationshipType { get; set; }

    public Nullable<System.DateTime> Last_Modified_Date { get; set; }

    public string Last_Modified_Authid { get; set; }

    public string Last_Modified_Uid { get; set; }

    public string Status { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public string SchoolAttended { get; set; }

    public Nullable<bool> IsStudent { get; set; }

}

}
