
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Akirs.client.DL
{

using System;
    using System.Collections.Generic;
    
public partial class IncomeSource
{

    public int ItbID { get; set; }

    public string EnrollmentID { get; set; }

    public int SourceOfIncomeID { get; set; }

    public decimal Amount { get; set; }

    public Nullable<System.DateTime> Last_Modified_Date { get; set; }

    public string Last_Modified_Authid { get; set; }

    public string Last_Modified_Uid { get; set; }

    public string Status { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<int> NHFFlag { get; set; }

    public Nullable<int> PensionFlag { get; set; }

    public string IncomeYear { get; set; }

    public string IsNew { get; set; }

}

}
