
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Akirs.client.DL
{

using System;
    using System.Collections.Generic;
    
public partial class menucontrol
{

    public int menuId { get; set; }

    public string menuName { get; set; }

    public string url { get; set; }

    public Nullable<int> parent { get; set; }

    public Nullable<int> Priority { get; set; }

    public string status { get; set; }

    public Nullable<bool> flag { get; set; }

    public string description { get; set; }

    public string tablename { get; set; }

    public string ResourceKey { get; set; }

}

}
