
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Akirs.client.DL
{

using System;
    using System.Collections.Generic;
    
public partial class MFBPANMAPPING
{

    public int itbid { get; set; }

    public Nullable<int> bankid { get; set; }

    public Nullable<long> PAN_Digit { get; set; }

    public Nullable<System.DateTime> createdate { get; set; }

    public string userid { get; set; }

    public string status { get; set; }

    public string PANPosition { get; set; }

}

}
