
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Akirs.client.DL
{

using System;
    using System.Collections.Generic;
    
public partial class NotificationProvider
{

    public long itbid { get; set; }

    public string NotificationClass { get; set; }

    public string ProviderName { get; set; }

    public string UserID { get; set; }

    public string NotificationPassword { get; set; }

    public string host { get; set; }

    public Nullable<int> portId { get; set; }

    public string ApiUrl { get; set; }

    public string KeyId { get; set; }

    public Nullable<int> Defaultflag { get; set; }

    public Nullable<System.DateTime> Last_Modified_Date { get; set; }

    public string Last_Modified_Authid { get; set; }

    public string Last_Modified_Uid { get; set; }

    public string Status { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public string AuthUserID { get; set; }

}

}
