
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Akirs.client.DL
{

using System;
    using System.Collections.Generic;
    
public partial class RemoteBank
{

    public int id { get; set; }

    public string RoutingNo { get; set; }

    public string BankName { get; set; }

    public Nullable<int> NoOfDays { get; set; }

    public string Bankshortname { get; set; }

    public Nullable<System.DateTime> Createdate { get; set; }

    public string status { get; set; }

    public string userid { get; set; }

    public string authorisedby { get; set; }

    public string authid { get; set; }

    public string CBNCode { get; set; }

}

}
