
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Akirs.client.DL
{

using System;
    using System.Collections.Generic;
    
public partial class RoleLimit
{

    public int itbID { get; set; }

    public Nullable<long> RoleId { get; set; }

    public string TransactionCode { get; set; }

    public Nullable<decimal> LimitAmount { get; set; }

    public string Status { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public string AdminUserID { get; set; }

    public string AuthUserID { get; set; }

}

}
