
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Akirs.client.DL
{

using System;
    using System.Collections.Generic;
    
public partial class roleAssignment
{

    public int roleAssgId { get; set; }

    public int roleId { get; set; }

    public int menuId { get; set; }

    public string userId { get; set; }

    public System.DateTime dateCreated { get; set; }

    public string status { get; set; }

    public Nullable<int> canInsert { get; set; }

    public Nullable<int> canDelete { get; set; }

    public Nullable<int> canUpdate { get; set; }

    public Nullable<int> canauth { get; set; }

    public Nullable<int> authId { get; set; }

    public Nullable<int> company { get; set; }

}

}
