
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Akirs.client.DL
{

using System;
    using System.Collections.Generic;
    
public partial class Salaryupload_temp
{

    public long ItbID { get; set; }

    public string EnrollmentID { get; set; }

    public string EmployeeID { get; set; }

    public string EmployeeName { get; set; }

    public Nullable<decimal> AnnualBasic { get; set; }

    public Nullable<decimal> AnnualHousing { get; set; }

    public Nullable<decimal> AnnualTransport { get; set; }

    public Nullable<decimal> AnnualMeal { get; set; }

    public Nullable<decimal> AnnualOthers { get; set; }

    public Nullable<decimal> GrossPay { get; set; }

    public Nullable<decimal> NHFContribution { get; set; }

    public Nullable<System.DateTime> Last_Modified_Date { get; set; }

    public string Last_Modified_Authid { get; set; }

    public string Last_Modified_Uid { get; set; }

    public string Status { get; set; }

    public Nullable<bool> VALIDATIONERRORSTATUS { get; set; }

    public string VALIDATIONERRORMESSAGE { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public string AuthUserID { get; set; }

    public Nullable<decimal> Pension { get; set; }

    public Nullable<decimal> Premium { get; set; }

    public Nullable<decimal> NHIS { get; set; }

    public Nullable<decimal> Others { get; set; }

}

}
