
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Akirs.client.DL
{

using System;
    using System.Collections.Generic;
    
public partial class SMSMessage
{

    public long itbid { get; set; }

    public string SMSContent { get; set; }

    public string PhoneNo { get; set; }

    public string SenderID { get; set; }

    public string SMSStatus { get; set; }

    public Nullable<System.DateTime> EntryDate { get; set; }

    public string bankfiid { get; set; }

}

}
