
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Akirs.client.DL
{

using System;
    using System.Collections.Generic;
    
public partial class tbl_BankCharges
{

    public long itbID { get; set; }

    public long BankID { get; set; }

    public string TransactionCode { get; set; }

    public int MFBChargeBasis { get; set; }

    public Nullable<decimal> MFBChargeToCustomer { get; set; }

    public Nullable<decimal> MFBNetAmount { get; set; }

    public int ZenithChargeBasis { get; set; }

    public Nullable<decimal> ZenithChargeToCustomer { get; set; }

    public Nullable<decimal> ZenithNetAmount { get; set; }

    public System.DateTime Createdate { get; set; }

    public string Status { get; set; }

    public string AdminUserID { get; set; }

    public string AuthUserID { get; set; }

}

}
