
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Akirs.client.DL
{

using System;
    using System.Collections.Generic;
    
public partial class TransactionLog
{

    public long itbID { get; set; }

    public string TransactionCode { get; set; }

    public System.DateTime TransactionDate { get; set; }

    public decimal Amount { get; set; }

    public Nullable<int> Chargecode { get; set; }

    public Nullable<decimal> TransactionFee { get; set; }

    public string AccountName { get; set; }

    public Nullable<decimal> BenAcctBalance { get; set; }

    public string FromBank { get; set; }

    public string ToBank { get; set; }

    public string TransactionReference { get; set; }

    public string FromAccountNumber { get; set; }

    public string ToAccountNumber { get; set; }

    public string Responsecode { get; set; }

    public string ResponseDescription { get; set; }

    public string DebitLegStatus { get; set; }

    public string CreditLegStatus { get; set; }

    public string Status { get; set; }

    public string DebitLegResponseCode { get; set; }

    public string DebitLegResponseDescription { get; set; }

    public string CreditLegResponseCode { get; set; }

    public string CreditLegResponseDescription { get; set; }

    public string Naration { get; set; }

    public string iSessionID { get; set; }

    public string ReversalResponse { get; set; }

    public string ReversalComment { get; set; }

    public string TransferSessionID { get; set; }

    public long MfbBankID { get; set; }

    public long ZenBankId { get; set; }

    public string FromProviderID { get; set; }

    public string ToProviderID { get; set; }

    public string FromBranch { get; set; }

    public string UserID { get; set; }

    public string TillAccountNo { get; set; }

    public Nullable<System.DateTime> Createdate { get; set; }

    public Nullable<System.TimeSpan> RequestStartTime { get; set; }

    public Nullable<System.TimeSpan> RequestEndTime { get; set; }

    public string ChequeNo { get; set; }

    public string ChequeAcctNo { get; set; }

    public string ChequeType { get; set; }

    public string RejectionComment { get; set; }

    public string CustAcctNo { get; set; }

    public Nullable<short> LimitStatus { get; set; }

    public int NoOfDays { get; set; }

    public string ReturnUserId { get; set; }

    public Nullable<bool> ReturnChequeFlag { get; set; }

    public string ReturnChequeReason { get; set; }

    public string MfbPtid { get; set; }

    public string ZenPtid { get; set; }

    public Nullable<short> NoOfExtension { get; set; }

    public Nullable<decimal> BookBalance { get; set; }

    public string PhoenixRefNo { get; set; }

}

}
