
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Akirs.client.DL
{

using System;
    using System.Collections.Generic;
    
public partial class WHTUPLOAD
{

    public long ItbID { get; set; }

    public string EnrollmentID { get; set; }

    public string VendorTINNO { get; set; }

    public string VendorName { get; set; }

    public Nullable<decimal> TaxRate { get; set; }

    public Nullable<decimal> TaxAmount { get; set; }

    public Nullable<System.DateTime> Last_Modified_Date { get; set; }

    public string Last_Modified_Authid { get; set; }

    public string Last_Modified_Uid { get; set; }

    public string Status { get; set; }

    public Nullable<bool> VALIDATIONERRORSTATUS { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public string AuthUserID { get; set; }

}

}
